"""Bucket table created

Revision ID: 03f30bd02b87
Revises: 464227cad1a8
Create Date: 2026-06-09 23:44:27.933065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03f30bd02b87'
down_revision: Union[str, Sequence[str], None] = '464227cad1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'companys', ['name'])
    op.create_unique_constraint(None, 'members', ['email'])
    op.create_unique_constraint(None, 'projects', ['name'])
    op.alter_column('roles', 'name',
               existing_type=postgresql.ENUM('SUPER_ADMIN', 'ADMIN', 'DEVELOPER', 'OWNER', 'COLLABORATOR', name='roleenum'),
               type_=sa.String(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'roles', ['name'])
    op.create_unique_constraint(None, 'tasks', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.alter_column('roles', 'name',
               existing_type=sa.String(),
               type_=postgresql.ENUM('SUPER_ADMIN', 'ADMIN', 'DEVELOPER', 'OWNER', 'COLLABORATOR', name='roleenum'),
               existing_nullable=False)
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'members', type_='unique')
    op.drop_constraint(None, 'companys', type_='unique')
    # ### end Alembic commands ###
