"""role  table created

Revision ID: 092a192a6e97
Revises: 38d2542eb860
Create Date: 2026-06-09 15:53:32.825776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092a192a6e97'
down_revision: Union[str, Sequence[str], None] = '38d2542eb860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('SUPER_ADMIN', 'ADMIN', 'DEVELOPER', 'OWNER', 'COLLABORATOR', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
