"""all table created with many relationship

Revision ID: 2c253ff96b91
Revises: d488d002ddfc
Create Date: 2026-06-10 10:04:17.153150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c253ff96b91'
down_revision: Union[str, Sequence[str], None] = 'd488d002ddfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_task_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('member_permission_mapping', 'action',
               existing_type=postgresql.ENUM('GRANT', 'REVOKE', name='statusenum'),
               type_=sa.Enum('GRANT', 'REVOKE', name='statusenum'),
               postgresql_using='action::text::statusenum',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member_permission_mapping', 'action',
               existing_type=sa.Enum('GRANT', 'REVOKE', name='statusenum'),
               type_=postgresql.ENUM('GRANT', 'REVOKE', name='statusenum'),
               existing_nullable=False)
    op.drop_table('member_task_mapping')
    # ### end Alembic commands ###


