"""company table created

Revision ID: 38d2542eb860
Revises: 29982095bd1a
Create Date: 2026-06-09 11:28:26.145990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d2542eb860'
down_revision: Union[str, Sequence[str], None] = '29982095bd1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=False),
    sa.Column('subcription', sa.Enum('ALL_FEATURE', 'HALF_FEATURE', 'BASIC_FEATURE', name='subscriptionenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companys')
    # ### end Alembic commands ###
