"""Project model for soft delete

Revision ID: 81bfbb59bea2
Revises: b6d6c1f729b2
Create Date: 2026-06-22 00:56:33.744342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81bfbb59bea2'
down_revision: Union[str, Sequence[str], None] = 'b6d6c1f729b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member_permission_mapping', 'action',
               existing_type=postgresql.ENUM('ACTIVE', 'PENDING', name='statusenum'),
               type_=sa.Enum('GRANT', 'REVOKE', name='statusenum'),
               existing_nullable=False)
    op.add_column('projects', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_deleted')
    op.drop_column('projects', 'is_archived')
    op.alter_column('member_permission_mapping', 'action',
               existing_type=sa.Enum('GRANT', 'REVOKE', name='statusenum'),
               type_=postgresql.ENUM('ACTIVE', 'PENDING', name='statusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
