"""Project INvite and Task Attchement Added3

Revision ID: b6d6c1f729b2
Revises: 45a7e83e08ac
Create Date: 2026-06-22 00:53:39.011614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6d6c1f729b2'
down_revision: Union[str, Sequence[str], None] = '45a7e83e08ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', name='invitestatus'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['members.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('task_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('member_permission_mapping', 'action',
               existing_type=postgresql.ENUM('ACTIVE', 'PENDING', name='statusenum'),
               type_=sa.Enum('GRANT', 'REVOKE', name='statusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member_permission_mapping', 'action',
               existing_type=sa.Enum('GRANT', 'REVOKE', name='statusenum'),
               type_=postgresql.ENUM('ACTIVE', 'PENDING', name='statusenum'),
               existing_nullable=False)
    op.drop_table('task_attachments')
    op.drop_table('project_invites')
    # ### end Alembic commands ###
