"""permission table created

Revision ID: c8b2eec07cd7
Revises: 092a192a6e97
Create Date: 2026-06-09 15:54:31.092039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b2eec07cd7'
down_revision: Union[str, Sequence[str], None] = '092a192a6e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('CREATE_TASK', 'UPLOAD_TASK', 'APPROVE_TASK', 'CHANGE_TASK_STATUS', 'ENABLE_NO_OF_HOURS_IN_BUCKET', 'ENABLE_PROGRESS_IN_BUCKET', name='permissionenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions')
    # ### end Alembic commands ###
