"""all table created

Revision ID: d488d002ddfc
Revises: 03f30bd02b87
Create Date: 2026-06-10 08:11:26.611575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd488d002ddfc'
down_revision: Union[str, Sequence[str], None] = '03f30bd02b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permission_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('member_permission_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('GRANT', 'REVOKE', name='statusenum'), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_project_role_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('comments', sa.Column('member_id', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('task_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'members', ['member_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'tasks', ['task_id'], ['id'])
    op.add_column('members', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'members', 'companys', ['company_id'], ['id'])
    op.add_column('projects', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('projects', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'companys', ['company_id'], ['id'])
    op.add_column('tasks', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tasks', sa.Column('project_id', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('bucket_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'members', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'buckets', ['bucket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'bucket_id')
    op.drop_column('tasks', 'creator_id')
    op.drop_column('tasks', 'project_id')
    op.drop_column('tasks', 'created_at')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'company_id')
    op.drop_column('projects', 'created_at')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_column('members', 'company_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'task_id')
    op.drop_column('comments', 'member_id')
    op.drop_column('comments', 'created_at')
    op.drop_table('member_project_role_mapping')
    op.drop_table('member_permission_mapping')
    op.drop_table('buckets')
    op.drop_table('role_permission_mapping')
    # ### end Alembic commands ###
