"""fixed some naming

Revision ID: de62ab096baa
Revises: e0b684724a47
Create Date: 2026-06-11 16:34:22.616069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de62ab096baa'
down_revision: Union[str, Sequence[str], None] = 'e0b684724a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member_permission_mapping', 'action',
               existing_type=postgresql.ENUM('ACTIVE', 'PENDING', name='statusenum'),
               type_=sa.Enum('GRANT', 'REVOKE', name='statusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member_permission_mapping', 'action',
               existing_type=sa.Enum('GRANT', 'REVOKE', name='statusenum'),
               type_=postgresql.ENUM('ACTIVE', 'PENDING', name='statusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
