"""all table created with many relationship executed

Revision ID: e51aff7cc0b0
Revises: 2c253ff96b91
Create Date: 2026-06-10 10:13:22.260777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e51aff7cc0b0'
down_revision: Union[str, Sequence[str], None] = '2c253ff96b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member_permission_mapping', 'action',
               existing_type=postgresql.ENUM('ACTIVE', 'PENDING', name='statusenum'),
               type_=sa.Enum('GRANT', 'REVOKE', name='statusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member_permission_mapping', 'action',
               existing_type=sa.Enum('GRANT', 'REVOKE', name='statusenum'),
               type_=postgresql.ENUM('ACTIVE', 'PENDING', name='statusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
